# Enable this when you're ready to use Cloudflared as ingress
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: platform
  source:
    path: platform/cloudflared
    repoURL: git@github.com:wagnerius/get-started.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
