# Configures ArgoCD to automatically sync all resources in the platform-applications directory
# as well as all sub-folders to the applications directory.

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Resources required for the platform.
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: platform-applications
    repoURL: git@github.com:wagnerius/get-started.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: Applications running on top of the platform.
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:wagnerius/get-started.git
        revision: HEAD
        directories:
          - path: applications/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: applications
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
      source:
        repoURL: git@github.com:wagnerius/get-started.git
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
